### ISSUE TITLE
Счетчик птиц

### ISSUE THREAD

**Issue by AndreyYunak** [CoolCoolOne/Spilliaert_birdsGame#2]
Мне кажется, нужен счетчик найденных птичек.
И можно выводить сообщение, если все птички найдены.

**Comment by CoolCoolOne** [comment]
Нужен счётчик и сообщение по типу "вы выйграли", согласен. Не знаю как это реализовать текущими средствами (библиотека работы с графикой p5). Потому птичка отображается не как просто картинка. Она рисуется с частотой frame rate поверх фона если мышка наведена. Кстати, с этой же частотой появляются кружочки синевы и темноты.
Поэтому если просто считать количество обнаружений, то получим много-много обнаружений если просто держать мышку на птичке всю игру, и это будет не то что нужно.

**Comment by CoolCoolOne** [comment]
Сделал показ счёта птиц после того как стемнело. 
Не выделяю отдельно что все найдены по этическим причинам: не всех нашёл - всё равно молодец!

**Comment by CoolCoolOne** [comment]
Классная задача, спасибо. Закрываю
