### ISSUE TITLE
Масштабирование

### ISSUE THREAD

**Issue by AndreyYunak** [CoolCoolOne/Spilliaert_birdsGame#3]
Поле с птичками приходится прокручивать. Можно ли сделать чтобы поле подстраивалось под размер экрана?
![image](https://github.com/CoolCoolOne/Spilliaert_birdsGame/assets/128552437/2474667d-f52f-4312-a450-e37b0020aabd)

**Comment by CoolCoolOne** [comment]
Не буду я это делать, надо всё переписывать) Все позиции делать относительными)
