### ISSUE TITLE
Отслеживание мыши

### ISSUE THREAD

**Issue by AndreyYunak** [CoolCoolOne/Spilliaert_birdsGame#4]
Можно ли сделать отображение мыши при движении по полю? 
Когда водишь мышкой по полю, нет ощущения что мышь отслеживается, по началу кажется, что что-то не работает.
Хотя, возможно, в этом есть смысл.. неожиданность

**Comment by CoolCoolOne** [comment]
спасибо. Добавил другую форму курсора. Возможно чуть поможет, но хотелось бы добавить подзорную трубу (окошечко) которую водишь по экрану. Пока не знаю как это сделать. По тем же причинам как и счётчик птиц. Может есть другая идея, что сделать, чтобы у пользователя было ощущение отслеживания??

**Comment by CoolCoolOne** [comment]
Добавил курсор в виде бинокля. Проверял работу в chrome. Закрываю задачу. Если не то, открой заново :)

**Comment by CoolCoolOne** [comment]
Так. Чёто без скачивания проекта не работает как надо)

**Comment by CoolCoolOne** [comment]
норм подгрузился кэш
вот такое д.б
![lupa3](https://github.com/CoolCoolOne/Spilliaert_birdsGame/assets/162994571/21f33e7c-714f-4ec0-b823-1dfead235e5b)
